### ISSUE TITLE
init docs section using gitbook

### ISSUE THREAD

**Issue by pwrinc** [cubbles/cubbles.github.io#3]
Because the Cubbles platform documentation and wiki will no longer be maintained at Atlassian Confluence there should be a new documentation section available under `cubbles.github.io/docs`.

**Tasks:**
- [x] create new `docs` branch containing the new documentation
- [x] init `docs` branch with gitbook
- [ ] add `deploy` npm script in `docs` branch for building gitbook and deploying it to `master` branch under `docs/` folder

**Comment by pwrinc** [comment]
__Solution description:__
Because we use tha latest version of hosted gitbook service and they won't support usage of `gitbook-cli` we created a seperate repository cubbles/gitbook which will be automatically synced to https://cubbles.gitbook.io/docs/.

For migrationg the exsiting documentation from Confluence to cubbles/gitbook there will be additional issues.

**Comment by hrbu** [comment]
make our gitbook public
